// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08oTLYsLmkFIuzUwQVFfeL4XDNC6-gGU',
    appId: '1:145447278228:web:208f20ba4d31a1754e0681',
    messagingSenderId: '145447278228',
    projectId: 'mysecondloginmiki',
    authDomain: 'mysecondloginmiki.firebaseapp.com',
    storageBucket: 'mysecondloginmiki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetAzlrE-pCDxEBtw7y2LZTacDRuotI2c',
    appId: '1:145447278228:android:f8050fda1034c53a4e0681',
    messagingSenderId: '145447278228',
    projectId: 'mysecondloginmiki',
    storageBucket: 'mysecondloginmiki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30NrdsRBsqK6OmX5dwvKboYAm5_dhhJ4',
    appId: '1:145447278228:ios:67f7a84d61916e554e0681',
    messagingSenderId: '145447278228',
    projectId: 'mysecondloginmiki',
    storageBucket: 'mysecondloginmiki.appspot.com',
    iosClientId: '145447278228-2u26l9ofapk7rd729fkd85h8rcqfek18.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC30NrdsRBsqK6OmX5dwvKboYAm5_dhhJ4',
    appId: '1:145447278228:ios:35a76d9eaafc5bb84e0681',
    messagingSenderId: '145447278228',
    projectId: 'mysecondloginmiki',
    storageBucket: 'mysecondloginmiki.appspot.com',
    iosClientId: '145447278228-9ss6v2inq69shtcig7gbgr69el3gh2aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
